### ISSUE TITLE
什么时候，日程？

### ISSUE THREAD

**Issue by sunphy** [jsconfcn/ningjs#1]
如何参加？

**Comment by xeodou** [comment]
Hi @sunphy 

2016年的JS 中国开发者大会定在9月初，售票开始时我们会在微博、twitter、微信群等等上发消息的。（尤其是早鸟票噢

**Comment by willin** [comment]
@xeodou 敢不敢邀请我进 github org

**Comment by xeodou** [comment]
@willin :cry:

**Comment by xeodou** [comment]
Done
