### ISSUE TITLE
Do you need more lecturers?

### ISSUE THREAD

**Issue by tylerlong** [jsconfcn/ningjs#11]
Hi, I am not sure if this is the right way to contact the organizers. But do you need more lecturers?

I am the author of [Markdown Plus](https://github.com/tylingsoft/markdown-plus) which has been starred 1200+ time on GitHub. I would like to attend the conf and give a short talk there. (10 minutes should be enough but of course the longer the better.)  

Recently I created a [Glip](https://glip.com/) client named [Glip Plus](https://github.com/tylerlong/glip-plus-dist). I used [JXA (JavaScript Automation)](https://developer.apple.com/library/mac/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/Introduction.html) to add lots of cool features such as screenshot and screen recording. I would like to share my experience with JXA to the audience which I am sure they will be interested. 

Please kindly let me know if it is possible and how I can submit my topic.

I look forward to your reply.

**Comment by xeodou** [comment]
Hi @tylerlong  

We are sorry about that, we don't accept the speakers application anymore, we closed the call for speakers 2 months ago. But welcome to join us at the event. ;)

**Comment by grokify** [comment]
Hi @xeodou I've used Glip Plus and the way it adds functionality using JXA is cool. Is it possible to hear this talk as a lightning talk?

How are the lightning talks selected?

**Comment by xeodou** [comment]
Hi @grokify  All lighting talks are chosen from all our attendees, who want share something cool to us. If you want share something cool at lighting talk , the only thing you need to do is stand up and share. ;)

**Comment by tylerlong** [comment]
Hi @xeodou, that sounds good to me. I will try my best to give a lightning talk.

**Comment by xeodou** [comment]
Done. Closing. Thanks for the comments.
