### ISSUE TITLE
票都没有了？

### ISSUE THREAD

**Issue by moreJs** [jsconfcn/ningjs#12]
还有其他渠道或者方式，可以买到票吗？

**Comment by xeodou** [comment]
Hi @moreJs  你好，多谢对我们的支持，很抱歉，我们的门票已经全部售罄。

**Comment by moreJs** [comment]
@xeodou  好遗憾啊，一不留神，就没有票了。

**Comment by li-ml** [comment]
@moreJs  帮我加张票，成吗？

**Comment by jasonlam-swatow** [comment]
你好，现在 NingJS 的票已售罄，但我申请购买了全价 685 的「赞助商赠票专用」票，但我只是开发者身份，请问有机会通过审核吗？有可能买到票吗？

**Comment by codeyuyu** [comment]
还有票么？

**Comment by xeodou** [comment]
谢谢大家对活动的支持，实在抱歉，由于场地限制我们对参会人数做了限制，现在我们的票已经售罄，如继续售票我们会告知，也可以关注我们的官方微博、微信获取最新消息。

**Comment by xeodou** [comment]
嗨 我们增加了少量的票，需要购买的东西可以继续购买了。

**Comment by tylerlong** [comment]
又没有了？手慢了，哎。。。

**Comment by xeodou** [comment]
不好意思啊，现在已经不在售票了

**Comment by 123qws** [comment]
请问现在还有票吗，我家就在中央路，好想去😥😥

**Comment by lisztj** [comment]
申请了Full Ticket 全价票（赞助商赠票专用），希望能通过审核。。。

**Comment by xeodou** [comment]
JSConf China 2016 is done. See you next year. ;) 
Closing
