### ISSUE TITLE
Looking for a video team for NingJS conf (before and during the event)

### ISSUE THREAD

**Issue by cocoyu** [jsconfcn/ningjs#4]
Hey guys, we are looking for a professional video team for  2016 NingJS conf. We need a 1**min promotional video be done by mid-May** and the video team to **record the two-day event (Sep.3-4) and edit it into a cool conference video**. 

If you know anyone, please pass the info to me ( **coco@wiredcraft.com**, or just leave a comment here)

**Comment by cocoyu** [comment]
![ningjs1](https://cloud.githubusercontent.com/assets/17328973/14043439/46ff2a8c-f2bf-11e5-9600-812ca776bb65.png)
![ningjs2](https://cloud.githubusercontent.com/assets/17328973/14043446/4f08448e-f2bf-11e5-9d6d-8b273145c4c3.png)

**Comment by xeodou** [comment]
Done. Closing.
