### ISSUE TITLE
折扣票和全价票有什么不同？

### ISSUE THREAD

**Issue by ianjiang** [jsconfcn/ningjs#7]
- 两种票价格不一样，有什么不同吗？
- 折扣票，点击购买进去后，没看见需要输入折扣码之类的，直接就可以购买？
- 如果享受相同的服务，为什么价格不一样呢？

**Comment by xeodou** [comment]
@ianjiang 

我们的购票页面有说明`本次大会所售不同类别门票皆享有相同权益。`，至于价格不一样是所有的票种都是按照时间先后的，买的越早折扣越大的策略。 至于权益没有任何不同点。折扣票的价格就是折扣以后的价格，可以直接购买.

**Comment by ianjiang** [comment]
谢谢回复。
