### ISSUE TITLE
买了带发票的 票 忘了填发票信息，可以改吗？

### ISSUE THREAD

**Issue by timqian** [jsconfcn/ningjs#9]

**Comment by xeodou** [comment]
@timqian  没问题的，你的订单号或者购票信息，还有需要修改的发票信息

**Comment by timqian** [comment]
好的，我发你邮箱？

**Comment by xeodou** [comment]
你发到 support@jsconf.cn 吧。

**Comment by timqian** [comment]
好的，十分感谢

**Comment by xeodou** [comment]
不客气呐，多谢对我们活动的支持。

Best

Xeodou

Twitter: @xeodou https://twitter.com/xeodou
Github: xeodou https://github.com/xeodou
